TagHelpersRazo/Models/Persona.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TagHelpersRazo.Models
{
    public class Persona
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(20)]
        public string Nombre { get; set; }
        [Range(0 ,20)]
        public string Edad { get; set; }
        public Pais Pais { get; set; }
        public string Pregunta { get; set; }
        public string Descripcion { get; set; }
    }

    public enum Pais
    {
        [Display(Name ="..ESCOGER..")]
        Desconocido = 0,
        [Display(Name ="Republica Dominicana")]
        RepDominicana = 1 ,
        Mexico = 2 ,
        [Display(Name ="Costa Rica")]
        ConstaRica = 3
    }
}

TagHelpersRazo/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TagHelpersRazo.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

TagHelpersRazo/Pages/BootstrapTag.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TagHelpersRazo.Pages
{
    public class BootstrapTagModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

TagHelpersRazo/Pages/Cache.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TagHelpersRazo.Pages
{
    public class CacheModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

TagHelpersRazo/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TagHelpersRazo.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

TagHelpersRazo/Pages/CustomTag.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TagHelpersRazo.Pages
{
    public class CustomTagModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

TagHelpersRazo/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TagHelpersRazo.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

TagHelpersRazo/Pages/Formulario.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using TagHelpersRazo.Models;

namespace TagHelpersRazo.Pages
{
    public class FormularioModel : PageModel
    {
        [BindProperty]
        public Persona Persona { get; set;}

        public List<SelectListItem> PreguntasSeguridad
        {
            get
            {
                string escogido = Persona?.Pregunta;
                var preguntas = ObtenerPreguntaDeSeguridad();
                var opciones = new List<SelectListItem>();
                foreach (var pregunta in preguntas)
                {
                    opciones.Add(new SelectListItem()
                    {
                        Text = pregunta,
                        Value = pregunta,
                        Selected = pregunta == escogido
                    });
                }

                return opciones;
            }
        }

        public void OnGet()
        {

        }
        
        private List<string> ObtenerPreguntaDeSeguridad()
        {
            return new List<string>
            {
                "¿Cual es la nacionalidad de su perro?",
                "¿Pepsi o Coca cola?",
                "¿Nombre de una persona que usted no conoce?"
            };
        }

        public void OnPost()
        {

        }

        [ValidateAntiForgeryToken]
        public void OnPostConToken()
        {

        }
    }
}

TagHelpersRazo/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TagHelpersRazo.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

TagHelpersRazo/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>Use this area to provide additional information.</p>

TagHelpersRazo/Pages/BootstrapTag.cshtml
@page
@model TagHelpersRazo.Pages.BootstrapTagModel
@{
    ViewData["Title"] = "BootstrapTag";
}

<h2>BootstrapTag</h2>
<h4>Modal bootstrap</h4>

<a href="#" bs-toggle-modal="simpleModalFromAnchor">
    Launch modal
</a>
<modal id="simpleModalFromAnchor"
       title="Modal Title">
    <modal-body>
        <h4>Something happened</h4>
        <p>Something happened</p>
    </modal-body>
</modal>


<!--

    https://github.com/dpaquette/TagHelperSamples

-->

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TagHelpersRazo/Pages/Cache.cshtml
@page
@model TagHelpersRazo.Pages.CacheModel
@{
    ViewData["Title"] = "Cache";
}

<h2>Cache</h2>

<span>Sin cache: @DateTime.Now</span>
<br />
<cache expirate-after="@TimeSpan.FromDays(2)">
    Con cache @DateTime.Now
</cache>

<!--
    Atributos;

    Expira en un fecha en espeficica:
        expires-on="new DateTime(2025,1,29,17,02,0)"

     Expira luego de habar transcurrido una cantidad de tiempo indicada
        expires-adter="TimeSpan.FromMinutes(2)"

    Expira si no se ha accedido al recurso luego de una cantidad de tiempo determinado;
        expires-sliding="TimeSpan.FromMinutes(2)"

    Varia el cache segub valor cabecera de la peticion Http
        vary-by-header="User-Agent"

    Varia el caché Según el usuairo
        vary-by-user: true

    .. Entre otros
-->

TagHelpersRazo/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100 
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TagHelpersRazo/Pages/CustomTag.cshtml
@page
@model TagHelpersRazo.Pages.CustomTagModel
@{
    ViewData["Title"] = "CustomTag";
    var aprovado = false;
}

<h2>Personalizado</h2>

<div Condition="aprovado">
    usted ha sido aprobado :)
</div>
<div Condition="!aprovado">
    Usted ha sido rechazado :(
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TagHelpersRazo/Pages/Formulario.cshtml
@page
@model TagHelpersRazo.Pages.FormularioModel
@{
    ViewData["Title"] = "Formulario";
}

<h2>Formulario</h2>

<h5>Token</h5>

<form method="post">
    <div class="form-group">
        <label asp-for="Persona.Nombre"></label>
        <input asp-for="Persona.Nombre" />
        <span asp-validation-for="Persona.Nombre" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Persona.Edad"></label>
        <input asp-for="Persona.Edad" />
        <span asp-validation-for="Persona.Edad" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Persona.Pais"></label>
        <select asp-for="Persona.Pais"
                asp-items="Html.GetEnumSelectList<Models.Pais>()"></select>
        <span asp-validation-for="Persona.Nombre" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Persona.Pregunta"></label>
        <select asp-for="Persona.Pregunta" asp-items="Model.PreguntasSeguridad">
            <option value="">--Escoger--</option>
        </select>
        <span asp-validation-for="Persona.Pregunta" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Persona.Descripcion"></label>
        <textarea asp-for="Persona.Descripcion"></textarea>
        <span asp-validation-for="Persona.Descripcion" class="text-danger"></span>
    </div>


    <input type="submit" name="enviar" value="Enviar" asp-page-handler="ConToken" />
</form>


<h5>Sin Token</h5>

<!form method="post">
    <div class="form-group">
        <label asp-for="Persona.Nombre"></label>
        <input asp-for="Persona.Nombre" />
        <span asp-validation-for="Persona.Nombre" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Persona.Edad"></label>
        <input asp-for="Persona.Edad" />
        <span asp-validation-for="Persona.Edad" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Persona.Pais"></label>
        <select asp-for="Persona.Pais"
                asp-items="Html.GetEnumSelectList<Models.Pais>()"></select>
        <span asp-validation-for="Persona.Nombre" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Persona.Pregunta"></label>
        <select asp-for="Persona.Pregunta" asp-items="Model.PreguntasSeguridad">
            <option value="">--Escoger--</option>
        </select>
        <span asp-validation-for="Persona.Pregunta" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Persona.Descripcion"></label>
        <textarea asp-for="Persona.Descripcion"></textarea>
        <span asp-validation-for="Persona.Descripcion" class="text-danger"></span>
    </div>


    <input type="submit" name="enviar" value="Enviar" asp-page-handler="ConToken" />
</!form>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TagHelpersRazo/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core Razor Pages</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?linkid=852130">Working with Razor Pages.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure App Service</a></li>
        </ul>
    </div>
</div>

TagHelpersRazo/Pages/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TagHelpersRazo</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-page="/Index" class="navbar-brand">TagHelpersRazo</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-page="/Index">Home</a></li>
                    <li><a asp-page="/Formulario">Formulario</a></li>
                    <li><a asp-page="/About">About</a></li>
                    <li><a asp-page="/Contact">Contact</a></li>
                    <li><a asp-page="/CustomTag">Custom Tag</a></li>
                    <li><a asp-page="/BootstrapTag">Bootstrap Tag</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - TagHelpersRazo</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>